---
apiVersion: v1
kind: Service
metadata:
  name: www-miketrout-dev-service
spec:
  type: NodePort
  selector:
    app: www-miketrout-dev
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
